In [44]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [45]:
Data = pd.read_csv('play_data.csv')
Data

day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [46]:
le = LabelEncoder()
Data['outlook'] = le.fit_transform(Data['outlook'])
Data['temp'] = le.fit_transform(Data['temp'])
Data['humidity'] = le.fit_transform(Data['humidity'])
Data['wind'] = le.fit_transform(Data['wind'])
Data['play'] = le.fit_transform(Data['play'])
Data

day  outlook  temp  humidity  wind  play
0    D1        2     1         0     1     0
1    D2        2     1         0     0     0
2    D3        0     1         0     1     1
3    D4        1     2         0     1     1
4    D5        1     0         1     1     1
5    D6        1     0         1     0     0
6    D7        0     0         1     0     1
7    D8        2     2         0     1     0
8    D9        2     0         1     1     1
9   D10        1     2         1     1     1
10  D11        2     2         1     0     1
11  D12        0     2         0     0     1
12  D13        0     1         1     1     1
13  D14        1     2         0     0     0

In [47]:
X = Data[['outlook','temp','humidity','wind']].values
X

array([[2, 1, 0, 1],
       [2, 1, 0, 0],
       [0, 1, 0, 1],
       [1, 2, 0, 1],
       [1, 0, 1, 1],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [2, 2, 0, 1],
       [2, 0, 1, 1],
       [1, 2, 1, 1],
       [2, 2, 1, 0],
       [0, 2, 0, 0],
       [0, 1, 1, 1],
       [1, 2, 0, 0]])

In [48]:
Y = Data['play'].values
Y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [49]:
X = X.reshape(len(X),4)
print(X)

[[2 1 0 1]
 [2 1 0 0]
 [0 1 0 1]
 [1 2 0 1]
 [1 0 1 1]
 [1 0 1 0]
 [0 0 1 0]
 [2 2 0 1]
 [2 0 1 1]
 [1 2 1 1]
 [2 2 1 0]
 [0 2 0 0]
 [0 1 1 1]
 [1 2 0 0]]


In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3 , random_state = 0)

In [52]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,Y_train)

GaussianNB()

In [53]:
Y_pred = model.predict(X_test)
Y_pred

array([0, 0, 0, 1, 1])

In [54]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
cm

array([[0, 0],
       [3, 2]], dtype=int64)

In [55]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(Y_test,Y_pred) * 100
acc

40.0

In [56]:
df = pd.DataFrame({'Actual Data ': Y_test, 'Predicted Data': Y_pred})
df

Actual Data   Predicted Data
0             1               0
1             1               0
2             1               0
3             1               1
4             1               1